backend:
  name: github
  branch: master # Branch to update (optional; defaults to master)
  repo: svenvs/PROTO-netlify-cms

media_folder: "src/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
- name: "blog" # Used in routes, e.g., /admin/collections/blog
  label: "Blog" # Used in the UI
  folder: "src/blog" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields: # The fields for each document, usually in front matter
    - {label: "Layout", name: "layout", widget: "hidden", default: "blogLayout"}
    - {label: "Group", name: "group", widget: "hidden", default: "blog"}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Tags", name: "tags", widget: "list", default: ["post"]}
    - {label: "Auhthor", name: "auhthor", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "datetime"}
    - {label: "Clickbait", name: "clickbait", widget: "text", default: "type here a small part of the story to lure them into reading the post"}
    - {label: "Body", name: "body", widget: "markdown"}
- name: "presentation" # Used in routes, e.g., /admin/collections/blog
  label: "PResentation" # Used in the UI
  folder: "src/presentation/slides" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields: # The fields for each document, usually in front matter
    - {label: "Layout", name: "layout", widget: "hidden", default: "blogDefault"}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Tags", name: "tags", widget: "hidden", default: "slides"}
    - {label: "Body", name: "body", widget: "markdown"}